import { DriverProfile, EVVehicle, ActiveDrivingTelemetry, TripRecord } from '@/types/telematics';

export const MOCK_DRIVER: DriverProfile = {
  id: 'drv_004',
  name: 'Budi Santoso',
  phone: '+62 812-9876-5432',
  role: 'Senior EV Shuttle Driver',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=160&q=80',
  totalBrigaCoins: 580,
  currentStreak: 4,
  averageEcoScore: 93.2,
  totalTripsCompleted: 148,
};

export const MOCK_VEHICLES: EVVehicle[] = [
  {
    id: 'ev_hyundai_ioniq_02',
    code: 'DRV-01',
    name: 'Hyundai Ioniq 5',
    model: 'Long Range 2WD',
    licensePlate: 'B 1024 DRV',
    batteryCapacityKwh: 72.6,
    currentSoC: 92,
    estimatedRangeKm: 435,
    hubLocation: 'Cikarang Dry Port Hub',
    status: 'available',
    efficiencyKwhPer100Km: 16.7,
  },
  {
    id: 'ev_byd_atto_01',
    code: 'DRV-02',
    name: 'BYD Atto 3',
    model: 'Extended Range',
    licensePlate: 'B 1892 DRV',
    batteryCapacityKwh: 60.48,
    currentSoC: 86,
    estimatedRangeKm: 390,
    hubLocation: 'Halim Perdanakusuma Hub',
    status: 'available',
    efficiencyKwhPer100Km: 15.5,
  },
  {
    id: 'ev_wuling_binguo_03',
    code: 'DRV-03',
    name: 'Wuling BinguoEV',
    model: 'Premium 410km',
    licensePlate: 'B 2341 DRV',
    batteryCapacityKwh: 37.9,
    currentSoC: 78,
    estimatedRangeKm: 295,
    hubLocation: 'Bandara Soekarno-Hatta T3',
    status: 'available',
    efficiencyKwhPer100Km: 12.8,
  },
];

export const INITIAL_HUD_TELEMETRY: ActiveDrivingTelemetry = {
  speedKmh: 68,
  maxSpeedKmh: 82,
  speedLimitKmh: 80,
  accelG: 0.35,
  drivingStatus: 'smooth',
  statusMessage: 'Smooth Driving',
  activeProfile: 'HIGHWAY_NORMAL',
  currentSoC: 84,
  estimatedRangeKm: 348,
  tripDurationSeconds: 2535,
  tripDistanceKm: 44.8,
  liveEcoScore: 95,
  gpsAccuracyMeters: 3.2,
  isGpsLocked: true,
  wakeLockActive: true,
  pollingRateHz: 1.0,
  osrmMatched: true,
};

export const MOCK_END_TRIP_RECORD: TripRecord = {
  trip_id: 'trk_jabo_98231',
  driver_id: 'drv_004',
  driver_name: 'Budi Santoso',
  vehicle_id: 'ev_hyundai_ioniq_02',
  vehicle_name: 'Hyundai Ioniq 5',
  license_plate: 'B 1024 DRV',
  start_time: '2026-09-28T06:00:00Z',
  end_time: '2026-09-28T07:15:00Z',
  profile_used: 'HIGHWAY_NORMAL',
  start_battery_soc: 92,
  end_battery_soc: 68,
  start_odometer_km: 14250.0,
  end_odometer_km: 14311.8,
  distance_km: 61.8,
  energy_used_soc_percent: 24,
  energy_used_kwh: 17.42,
  telemetry_summary: {
    harsh_accelerations: 1,
    harsh_brakings: 0,
    idle_duration_seconds: 180,
    average_speed_kmh: 68.4,
    max_speed_kmh: 82.1,
    interpolated_gaps: 0,
  },
  eco_score: 94,
  eco_grade: 'A+',
  eco_grade_title: 'Eco Master',
  tokens_earned: 70,
  token_breakdown: {
    base_reward: 10,
    eco_multiplier: 2.0,
    multiplier_reward: 20,
    streak_bonus: 50,
    total_reward: 70,
  },
  trip_hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  verification_status: 'VERIFIED',
  esg_co2_avoided_kg: 9.88,
};
